name: A workflow for my Hello World file
on: push
env:
  EnvType: DEV
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona" 

      - name: Set the environment variable
        env: 
          access_id: ${{ secrets.{EnvType}_AWS_SECRET_ACCESS_ID }}
        run: |
          temp=`echo ${access_id}`
          echo $temp